name: hotel_booking
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  dio: ^5.7.0
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  auto_route: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Code Generation
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  auto_route_generator: ^9.0.0
  mockito: ^5.4.4
  get_it: ^8.0.2

flutter:
  uses-material-design: true
